version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./application:/application
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
#    depends_on:
#      - db
#  db:
#    image: postgres:12.1-alpine
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=supersecretpassword
#    ports:
#      - "5432:5432"
#    volumes:
#      - /Users/kathan/Documents/django-docker/pgdata:/var/lib/postgresql/data